### ISSUE TITLE
Hue light wont accept RGB value

### ISSUE THREAD

**Issue by Jismon003** [mauricedominic/node-red-contrib-huemagic#14]
Im trying to test setting a hue light to RGB 10,10,10, however wehn i get the bulbs data its set to 171,170,171. Flow is below

[
    {
        "id": "dd2df22722c5e65c",
        "type": "inject",
        "z": "1cedbe4aa3394538",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1240,
        "y": 360,
        "wires": [
            [
                "28e907908cee59a3"
            ]
        ]
    },
    {
        "id": "28e907908cee59a3",
        "type": "function",
        "z": "1cedbe4aa3394538",
        "name": "function 371",
        "func": "msg = {\n    payload: \n    {\n        \"rgb\": [10,10,10]\n    }\n}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1410,
        "y": 360,
        "wires": [
            [
                "8d3052c682d6b204"
            ]
        ]
    },
    {
        "id": "8d3052c682d6b204",
        "type": "hue-light",
        "z": "1cedbe4aa3394538",
        "name": "Office Top",
        "bridge": "5649160bdf709fe2",
        "lightid": "fb93d087-2c10-4d70-b073-b3584bd2ad47",
        "colornamer": true,
        "skipevents": false,
        "initevents": false,
        "x": 1670,
        "y": 360,
        "wires": [
            [
                "76be6fe374ea1ccd",
                "f5990a275943e8ac",
                "4dcab20bfa01d008"
            ]
        ]
    },
    {
        "id": "4dcab20bfa01d008",
        "type": "debug",
        "z": "1cedbe4aa3394538",
        "name": "debug 93",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 1480,
        "y": 220,
        "wires": []
    },
    {
        "id": "5649160bdf709fe2",
        "type": "hue-bridge",
        "name": "Philips hue",
        "bridge": "10.59.24.135",
        "key": "Co1qDHrQAk3er6wDwQ8nDCF8rRgyGI9YGIQxIwNJ",
        "worker": 10,
        "autoupdates": true
    }
]

**Comment by mauricedominic** [comment]
color not supported by hue
