### ISSUE TITLE
Cannot fetch scenes or groups

### ISSUE THREAD

**Issue by brian-gates** [mauricedominic/node-red-contrib-huemagic#2]
I'm seeing 500 Internal Server Error when attempting to fetch scenes or groups.

I am able to connect to the bridge successfully and get debug information from it.

**Screenshots**
![image](https://user-images.githubusercontent.com/97096/213982914-9299dcff-c478-47fc-9c30-46481c88dce3.png)
![image](https://user-images.githubusercontent.com/97096/213983226-b76049c5-c7e0-463b-9508-32f13ad522ed.png)

**Please complete the following information:**
 - Node-RED version: 14.0.1 
 - NodeJS version: Not sure how to check this
 - Device running Node-RED: Home Assistant OS

**Comment by mauricedominic** [comment]
Can you let me know what version of node-red-contrib-huemagic-fork you are on? Regarding your Node-Red version, I presume you are referring to the HA node-red plugin v 14.0.1?

**Comment by brian-gates** [comment]
node-red-contrib-huemagic-fork is version 4.2.6

![image](https://user-images.githubusercontent.com/97096/214204437-3af39b20-7952-4472-a9dc-43872dacd2fb.png)

> I presume you are referring to the HA node-red plugin v 14.0.1?

Yep!

![image](https://user-images.githubusercontent.com/97096/214204284-e6cbc95f-c09c-408d-8325-eee37ae50cc1.png)

**Comment by mauricedominic** [comment]
I have been trying to reproduce the issue you are facing. But have not been able to do so using HA 2023.1.7 with HA community addon node-red 14.0.1 and node-red-contrib-huemagic-fork 4.2.6. Are you able to share more information on your setup, such as current HA version, Hue Bridge firmware version and the Node-Red log from HA?

**Comment by brian-gates** [comment]
Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230201.0 - latest 

Hue firmware: BSB002 | 1.55.1955082050

**Comment by brian-gates** [comment]
Aaaand today it works... 🤷🏻‍♂️

**Comment by brian-gates** [comment]
Thank you for your time and effort looking into this!
