### ISSUE TITLE
Support for Hue Tap Dial Switch

### ISSUE THREAD

**Issue by arachnida** [mauricedominic/node-red-contrib-huemagic#6]
Hi,

I bought one of the Tap Dial Switches and managed to get the 4 buttons working but it seems there is no support for the dimmer dial functionality. Is it possible to implement the [/resource/relative_rotary](https://developers.meethue.com/develop/hue-api-v2/api-reference/#panel_resource_relative_rotary) in some way? I don't mind beta testing.

Many thanks and greetings from Belgium!

**Comment by rainbow-six3** [comment]
Hi. Same Problem here. I am currently developing the feature for the Dial and i am almost done. Pull-Request will be followed shortly.

**Comment by mauricedominic** [comment]
Thanks @rainbow-six3 ! Added to release 4.2.7

**Comment by arachnida** [comment]
Many Thanks!
